# Generated by Django 4.2 on 2023-04-19 17:50

import autopujcovny.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autopujcovna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název autopůjčovny', max_length=100, verbose_name='Název')),
                ('adresa', models.CharField(help_text='Zadejte adresu autopůjčovny', max_length=200, verbose_name='Adresa')),
                ('telefon', models.CharField(help_text='Zadejte telefonní číslo autopůjčovny (včetně předvolby)', max_length=20, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platné telefonní číslo.', regex='^(\\+420)? ?[1-9][0-9]{2}( ?[0-9]{3}){2}$')], verbose_name='Telefon')),
                ('email', models.EmailField(help_text='Zadejte e-mailovou adresu autopůjčovny', max_length=254, validators=[django.core.validators.EmailValidator('Neplatný e-mail.')], verbose_name='E-mail')),
                ('logo', models.ImageField(blank=True, help_text='Nahrajte logo autopůjčovny', null=True, upload_to=autopujcovny.models.Autopujcovna.logo_upload_path, verbose_name='Logo')),
                ('informace', models.TextField(blank=True, help_text='Zadejte další informace o autopůjčovně', verbose_name='Informace')),
            ],
            options={
                'verbose_name': 'Autopůjčovna',
                'verbose_name_plural': 'Autopůjčovny',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaceni', models.CharField(help_text='Zadejte označení vozu', max_length=50, verbose_name='Označení auta')),
                ('spz', models.CharField(help_text='Státní poznávací značka', max_length=8, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{8}$')], verbose_name='SPZ')),
                ('rok_vyroby', models.PositiveSmallIntegerField(blank=True, help_text='Zadejte rok výroby', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2023)], verbose_name='Rok výroby')),
                ('pocet_mist', models.PositiveSmallIntegerField(blank=True, default=4, help_text='Zadejte počet míst ve vozu (1-9)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Počet míst')),
                ('prevodovka', models.CharField(choices=[('automatická', 'Automatická'), ('manuální', 'Manuální')], default='manuální', max_length=15, verbose_name='Typ převodovky')),
                ('palivo', models.CharField(choices=[('benzín', 'Benzín'), ('nafta', 'Nafta'), ('lpg', 'LPG')], default='benzín', max_length=10, verbose_name='Typ paliva')),
                ('vykon', models.PositiveIntegerField(blank=True, help_text='Zadejte výkon motoru v kW', null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Výkon motoru v kW')),
                ('vybava', models.TextField(blank=True, help_text='Uveďte vybavení vozu', null=True, verbose_name='Výbava vozu')),
                ('cena', models.PositiveIntegerField(help_text='Zadejte částku v Kč', validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Cena za 1 hod.')),
                ('foto', models.ImageField(blank=True, help_text='Zde můžete vložit fotografii vozu', null=True, upload_to='auto/', verbose_name='Fotka vozu')),
                ('autopujcovna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopujcovny.autopujcovna', verbose_name='Autopůjčovna')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auta',
                'ordering': ['autopujcovna', '-rok_vyroby'],
            },
        ),
    ]
