# Generated by Django 4.2 on 2023-04-19 19:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopujcovny', '0002_zakaznik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hodnoceni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.DateTimeField(auto_now=True)),
                ('komentar', models.TextField(help_text='Okomentujte úroveň služeb autopůjčovny', verbose_name='Komentář zákazníka')),
                ('spokojenost', models.PositiveSmallIntegerField(help_text='Vyjádřete svou spokojenost se službami autopůjčovny (0 až 100 %)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Spokojenost se službami')),
                ('autopujcovna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopujcovny.autopujcovna', verbose_name='Autopůjčovna')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopujcovny.zakaznik', verbose_name='Zákazník')),
            ],
            options={
                'verbose_name': 'Hodnocení zákazníka',
                'verbose_name_plural': 'Hodnocení zákazníků',
                'ordering': ['-spokojenost'],
            },
        ),
    ]
