# Generated by Django 4.2 on 2023-04-22 12:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopujcovny', '0003_hodnoceni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronajem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vypujceno', models.DateTimeField(default=datetime.datetime(2023, 4, 22, 12, 22, 39, 199774, tzinfo=datetime.timezone.utc), help_text='Datum a čas zahájení pronájmu', verbose_name='Vypůjčeno')),
                ('vraceno', models.DateTimeField(blank=True, help_text='Datum a čas ukončení pronájmu', null=True, verbose_name='Vráceno')),
                ('ujeto', models.PositiveIntegerField(default=0, help_text='Zadejte počet ujetých km', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Ujeto km')),
                ('poznamka', models.TextField(blank=True, help_text='Uveďte případné zjištěné závady a problémy', verbose_name='Poznámka')),
                ('platba', models.CharField(choices=[('hotovost', 'Hotovost'), ('platební karta', 'Platební karta'), ('převod', 'Převodem na účet')], help_text='Zvolte způsob úhrady', max_length=20, verbose_name='Způsob úhrady')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopujcovny.auto', verbose_name='Auto')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopujcovny.zakaznik', verbose_name='Zákazník')),
            ],
            options={
                'verbose_name': 'Pronájem auta',
                'verbose_name_plural': 'Pronájmy aut',
                'ordering': ['auto', '-vypujceno'],
            },
        ),
    ]
